version: "3.5"

services:
  ms:
    container_name: ${MICROSERVICE}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKDIR: ${WORKDIR}
        MAXSIZELOG: ${MAXSIZELOG}
        RETAINLOG: ${RETAINLOG}
        MICROSERVICE: ${MICROSERVICE}
        ACTIVEBRANCH: ${ACTIVEBRANCH}
        VERSION: ${VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: ${MAXSIZELOG}
        max-file: ${RETAINLOG}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      VERSION: ${VERSION}
    volumes:
      - "../${MICROSERVICE}:${WORKDIR}/${MICROSERVICE}"
      - "/opt/config:/opt/config"
    ports:
      - "${PORTHTTP}:${PORTHTTP}"
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: ${IP}

networks:
  app_net:
    external:
      name: ${NETWORKNAME}
